/**
 * Recurring expense rules.
 *
 * The web client **manages rules but never generates expenses from them.** Generation is a
 * write driven by `lastGeneratedDate`, and Android (WorkManager) and iOS (launch catch-up)
 * already both do it against the same field. Adding a third writer racing the other two would
 * duplicate rows whenever two clients caught up at once, and a browser tab is the worst
 * candidate for the job: it only runs while someone happens to have it open.
 *
 * So a rule created here is picked up and generated by whichever mobile client opens next,
 * using the shared `RecurringScheduleCalculator` that both already call.
 */
import { collection, deleteDoc, doc, onSnapshot, setDoc } from 'firebase/firestore'

import { db } from '../firebase'
import type { PaymentWire, RecurringExpense, RecurringFrequency } from '../types'
import type { Unsubscribe } from './expenses'
import { millis, millisOrNull } from './wire'

const recurringCollection = (householdId: string) =>
  collection(db, 'households', householdId, 'recurring')

export const FREQUENCY_LABELS: Record<RecurringFrequency, string> = {
  0: 'Daily',
  1: 'Weekly',
  2: 'Monthly',
  3: 'Yearly',
}

function decode(householdId: string, id: string, data: Record<string, unknown>): RecurringExpense {
  return {
    id,
    householdId,
    amount: Number(data.amount ?? 0),
    categoryId: (data.categoryId as string) ?? '',
    categoryName: (data.categoryName as string) ?? '',
    notes: (data.notes as string) ?? '',
    addedBy: (data.addedBy as string) ?? '',
    addedByName: (data.addedByName as string) ?? '',
    // Stored as the enum ordinal; 2 (Monthly) is the fallback all three clients use.
    frequency: (Number(data.frequency ?? 2) as RecurringFrequency),
    dayOfWeek: data.dayOfWeek == null ? null : Number(data.dayOfWeek),
    dayOfMonth: data.dayOfMonth == null ? null : Number(data.dayOfMonth),
    monthOfYear: data.monthOfYear == null ? null : Number(data.monthOfYear),
    startDate: millis(data.startDate),
    endDate: millisOrNull(data.endDate),
    lastGeneratedDate: millisOrNull(data.lastGeneratedDate),
    isActive: data.isActive !== false,
    paymentMethod: ((data.paymentMethod as PaymentWire) ?? '') as PaymentWire,
    createdAt: millis(data.createdAt),
  }
}

export function observeRecurring(
  householdId: string,
  onChange: (rules: RecurringExpense[]) => void,
  onError: (error: Error) => void,
): Unsubscribe {
  return onSnapshot(
    recurringCollection(householdId),
    (snapshot) =>
      onChange(
        snapshot.docs
          .map((d) => decode(householdId, d.id, d.data()))
          .sort((a, b) => b.createdAt - a.createdAt),
      ),
    onError,
  )
}

export async function upsertRecurring(rule: RecurringExpense): Promise<void> {
  // Optional fields are omitted rather than written as null, matching the mobile clients —
  // a stored null would decode to 0 on a client using `getLong`.
  const data: Record<string, unknown> = {
    householdId: rule.householdId,
    amount: rule.amount,
    categoryId: rule.categoryId,
    categoryName: rule.categoryName,
    notes: rule.notes,
    addedBy: rule.addedBy,
    addedByName: rule.addedByName,
    frequency: rule.frequency,
    startDate: rule.startDate,
    isActive: rule.isActive,
    paymentMethod: rule.paymentMethod,
    createdAt: rule.createdAt,
  }
  if (rule.dayOfWeek != null) data.dayOfWeek = rule.dayOfWeek
  if (rule.dayOfMonth != null) data.dayOfMonth = rule.dayOfMonth
  if (rule.monthOfYear != null) data.monthOfYear = rule.monthOfYear
  if (rule.endDate != null) data.endDate = rule.endDate
  // Preserved on edit: dropping it would make every mobile client regenerate the whole
  // backlog from `startDate`.
  if (rule.lastGeneratedDate != null) data.lastGeneratedDate = rule.lastGeneratedDate

  await setDoc(doc(recurringCollection(rule.householdId), rule.id), data)
}

export async function deleteRecurring(householdId: string, id: string): Promise<void> {
  await deleteDoc(doc(recurringCollection(householdId), id))
}
