import { useCallback, useState } from 'react'

import { PageHead } from '../components/Layout'
import { Card, Empty, Field, Icon, Modal, Notice, Segmented, Spinner, formatDate, fromDateInput, toDateInput } from '../components/ui'
import { useCollection, useHouseholdData } from '../data/HouseholdData'
import { FREQUENCY_LABELS, deleteRecurring, observeRecurring, upsertRecurring } from '../data/recurring'
import { useSession } from '../session/SessionProvider'
import { money, paymentMethods } from '../shared'
import type { PaymentWire, RecurringExpense, RecurringFrequency } from '../types'

export function Recurring() {
  const session = useSession()
  const householdId = session.household.id
  const canManage = session.allows('manageSharedConfig')
  const { categories } = useHouseholdData()

  const subscribe = useCallback(
    (onChange: (rows: RecurringExpense[]) => void, onError: (error: Error) => void) =>
      observeRecurring(householdId, onChange, onError),
    [householdId],
  )
  const { rows, loading, error } = useCollection<RecurringExpense>(subscribe, [householdId])

  const [editing, setEditing] = useState<RecurringExpense | null>(null)
  const [creating, setCreating] = useState(false)

  const toggleActive = async (rule: RecurringExpense) => {
    try {
      await upsertRecurring({ ...rule, isActive: !rule.isActive })
    } catch (caught) {
      window.alert((caught as Error)?.message ?? 'Could not update.')
    }
  }

  return (
    <>
      <PageHead title="Recurring" subtitle="Rules that create an expense on a schedule.">
        {canManage && (
          <button className="btn primary" type="button" onClick={() => setCreating(true)}>
            <Icon name="add" />
            New rule
          </button>
        )}
      </PageHead>

      {error != null && (
        <div style={{ marginBottom: 16 }}>
          <Notice kind="error">{error}</Notice>
        </div>
      )}

      <div style={{ marginBottom: 16 }}>
        {/* Being explicit about this avoids the obvious support question, and about a real
            design decision rather than a missing feature. */}
        <Notice>
          Rules are created and edited here, but the expenses themselves are generated by the
          Android or iOS app the next time it opens. A browser tab is not a reliable scheduler,
          and a third writer racing the two mobile clients would duplicate rows.
        </Notice>
      </div>

      {!canManage && (
        <div style={{ marginBottom: 16 }}>
          <Notice>Recurring rules are managed by the household owner.</Notice>
        </div>
      )}

      {loading ? (
        <Card>
          <Spinner label="Loading rules…" />
        </Card>
      ) : rows.length === 0 ? (
        <Card>
          <Empty
            icon="autorenew"
            title="No recurring rules"
            action={
              canManage ? (
                <button className="btn primary" type="button" onClick={() => setCreating(true)}>
                  Create the first one
                </button>
              ) : undefined
            }
          >
            Useful for rent, the milk bill, a subscription — anything that repeats.
          </Empty>
        </Card>
      ) : (
        <Card>
          <div className="list">
            {rows.map((rule) => (
              <div className="list-row" key={rule.id}>
                <div style={{ flex: 1, minWidth: 0 }}>
                  <div className="title">
                    {rule.notes.trim() !== '' ? rule.notes : rule.categoryName}
                    {!rule.isActive && (
                      <span className="badge" style={{ marginLeft: 8 }}>
                        Paused
                      </span>
                    )}
                  </div>
                  <div className="meta">
                    <span>{FREQUENCY_LABELS[rule.frequency]}</span>
                    <span>·</span>
                    <span>{rule.categoryName}</span>
                    <span>·</span>
                    <span>from {formatDate(rule.startDate)}</span>
                    {rule.lastGeneratedDate != null && (
                      <>
                        <span>·</span>
                        <span>last run {formatDate(rule.lastGeneratedDate)}</span>
                      </>
                    )}
                  </div>
                </div>
                <div className="amount">{money(rule.amount)}</div>
                {canManage && (
                  <div className="actions">
                    <button className="btn ghost" type="button" onClick={() => void toggleActive(rule)}>
                      <Icon name={rule.isActive ? 'pause' : 'play_arrow'} size={17} />
                    </button>
                    <button className="btn ghost" type="button" onClick={() => setEditing(rule)}>
                      <Icon name="edit" size={17} />
                    </button>
                    <button
                      className="btn ghost"
                      type="button"
                      onClick={() => {
                        if (window.confirm('Delete this rule? Expenses it already created stay.'))
                          void deleteRecurring(householdId, rule.id)
                      }}
                    >
                      <Icon name="delete" size={17} />
                    </button>
                  </div>
                )}
              </div>
            ))}
          </div>
        </Card>
      )}

      {(creating || editing != null) && (
        <RecurringForm
          categories={categories.map((c) => ({ id: c.id, name: c.name }))}
          existing={editing ?? undefined}
          householdId={householdId}
          uid={session.uid}
          displayName={session.displayName}
          onClose={() => {
            setCreating(false)
            setEditing(null)
          }}
        />
      )}
    </>
  )
}

function RecurringForm({
  categories,
  existing,
  householdId,
  uid,
  displayName,
  onClose,
}: {
  categories: Array<{ id: string; name: string }>
  existing?: RecurringExpense
  householdId: string
  uid: string
  displayName: string
  onClose: () => void
}) {
  const [amount, setAmount] = useState(existing ? String(existing.amount) : '')
  const [categoryId, setCategoryId] = useState(existing?.categoryId ?? categories[0]?.id ?? '')
  const [frequency, setFrequency] = useState<RecurringFrequency>(existing?.frequency ?? 2)
  const [dayOfMonth, setDayOfMonth] = useState(String(existing?.dayOfMonth ?? 1))
  const [dayOfWeek, setDayOfWeek] = useState(String(existing?.dayOfWeek ?? 1))
  const [startDate, setStartDate] = useState(toDateInput(existing?.startDate ?? Date.now()))
  const [notes, setNotes] = useState(existing?.notes ?? '')
  const [payment, setPayment] = useState<PaymentWire>(existing?.paymentMethod ?? 'upi')
  const [error, setError] = useState('')
  const [busy, setBusy] = useState(false)

  const parsed = Number(amount)
  const valid = Number.isFinite(parsed) && parsed > 0 && categoryId !== ''

  const submit = async (event: React.FormEvent) => {
    event.preventDefault()
    if (!valid) {
      setError('Enter an amount above zero and pick a category.')
      return
    }
    setBusy(true)
    setError('')
    try {
      await upsertRecurring({
        id: existing?.id ?? crypto.randomUUID(),
        householdId,
        amount: parsed,
        categoryId,
        categoryName: categories.find((c) => c.id === categoryId)?.name ?? '',
        notes: notes.trim(),
        addedBy: existing?.addedBy ?? uid,
        addedByName: existing?.addedByName ?? displayName,
        frequency,
        // Only the field the chosen frequency actually uses is written; the rest stay null so
        // the shared schedule calculator is not handed a contradictory rule.
        dayOfWeek: frequency === 1 ? Number(dayOfWeek) : null,
        dayOfMonth: frequency === 2 || frequency === 3 ? Number(dayOfMonth) : null,
        monthOfYear: frequency === 3 ? new Date(fromDateInput(startDate)).getMonth() + 1 : null,
        startDate: fromDateInput(startDate),
        endDate: existing?.endDate ?? null,
        lastGeneratedDate: existing?.lastGeneratedDate ?? null,
        isActive: existing?.isActive ?? true,
        paymentMethod: payment,
        createdAt: existing?.createdAt ?? Date.now(),
      })
      onClose()
    } catch (caught) {
      setError((caught as Error)?.message ?? 'Could not save.')
      setBusy(false)
    }
  }

  return (
    <Modal
      title={existing ? 'Edit rule' : 'New recurring rule'}
      onClose={onClose}
      actions={
        <>
          <button className="btn ghost" type="button" onClick={onClose} disabled={busy}>
            Cancel
          </button>
          <button className="btn primary" type="submit" form="recurring-form" disabled={busy || !valid}>
            {busy ? 'Saving…' : 'Save'}
          </button>
        </>
      }
    >
      {error !== '' && (
        <div style={{ marginBottom: 14 }}>
          <Notice kind="error">{error}</Notice>
        </div>
      )}
      <form id="recurring-form" onSubmit={submit}>
        <Field label="Amount" hint={parsed > 0 ? money(parsed) : undefined}>
          <input
            type="number"
            inputMode="decimal"
            min="0"
            step="0.01"
            value={amount}
            onChange={(event) => setAmount(event.target.value)}
            autoFocus
            required
          />
        </Field>

        <Field label="Category">
          <select value={categoryId} onChange={(event) => setCategoryId(event.target.value)} required>
            {categories.map((category) => (
              <option key={category.id} value={category.id}>
                {category.name}
              </option>
            ))}
          </select>
        </Field>

        <Field label="Frequency">
          <Segmented
            options={([0, 1, 2, 3] as RecurringFrequency[]).map((value) => ({
              value: String(value),
              label: FREQUENCY_LABELS[value],
            }))}
            value={String(frequency)}
            onChange={(value) => setFrequency(Number(value) as RecurringFrequency)}
          />
        </Field>

        {frequency === 1 && (
          <Field label="Day of week">
            <select value={dayOfWeek} onChange={(event) => setDayOfWeek(event.target.value)}>
              {['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'].map(
                (label, index) => (
                  <option key={label} value={index + 1}>
                    {label}
                  </option>
                ),
              )}
            </select>
          </Field>
        )}

        {(frequency === 2 || frequency === 3) && (
          <Field
            label="Day of month"
            hint="31 falls back to the last day in shorter months."
          >
            <input
              type="number"
              min="1"
              max="31"
              value={dayOfMonth}
              onChange={(event) => setDayOfMonth(event.target.value)}
            />
          </Field>
        )}

        <Field label="Starts on">
          <input
            type="date"
            value={startDate}
            onChange={(event) => setStartDate(event.target.value)}
            required
          />
        </Field>

        <Field label="Payment method">
          <Segmented
            options={paymentMethods().map((method) => ({
              value: method.wire,
              label: `${method.emoji} ${method.label}`,
            }))}
            value={payment}
            onChange={setPayment}
          />
        </Field>

        <Field label="Notes">
          <input
            value={notes}
            onChange={(event) => setNotes(event.target.value)}
            placeholder="e.g. Flat rent"
            maxLength={200}
          />
        </Field>
      </form>
    </Modal>
  )
}
