import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

export default defineConfig({
  plugins: [react()],
  build: {
    outDir: 'dist',
    // No source maps in the deployed bundle. Vite embeds `sourcesContent`, so a map is the
    // complete readable TypeScript of this client — 4.5MB of it — served to anyone who opens
    // devtools. Flip to true temporarily to debug a production problem.
    sourcemap: false,
  },
  resolve: {
    // The shared module is a `file:` dependency, so npm symlinks it to
    // shared/build/dist/js/productionLibrary. By default Vite resolves imports from a module's
    // REAL path, and node resolution from there walks up out of web/ entirely — so the Kotlin
    // output's own dependencies (@js-joda/core, format-util) are never found in
    // web/node_modules. Preserving symlinks keeps resolution anchored inside web/.
    preserveSymlinks: true,
  },
  // Kotlin/JS output is regenerated by Gradle; pre-bundling it would serve a stale copy and
  // make a rebuilt shared module appear not to take effect.
  optimizeDeps: { exclude: ['expensetracker-shared'] },
})
